CREATE TABLE IF NOT EXISTS dataset_import (id INT PRIMARY KEY, imported_at TIMESTAMP NOT NULL);
CREATE TABLE IF NOT EXISTS skill (id VARCHAR(80) PRIMARY KEY, name VARCHAR(200) NOT NULL, type VARCHAR(20) NOT NULL, category VARCHAR(100), description TEXT);
CREATE TABLE IF NOT EXISTS role_profile (id INT PRIMARY KEY, role_name VARCHAR(100) NOT NULL, grade VARCHAR(20) NOT NULL, UNIQUE(role_name, grade));
CREATE TABLE IF NOT EXISTS role_requirement (profile_id INT NOT NULL, skill_id VARCHAR(80) NOT NULL, required_level INT NOT NULL, critical BOOLEAN NOT NULL, PRIMARY KEY(profile_id,skill_id), FOREIGN KEY(profile_id) REFERENCES role_profile(id), FOREIGN KEY(skill_id) REFERENCES skill(id), CHECK(required_level BETWEEN 0 AND 5));
CREATE TABLE IF NOT EXISTS employee (id VARCHAR(30) PRIMARY KEY, full_name VARCHAR(200) NOT NULL, department VARCHAR(100), role_name VARCHAR(100) NOT NULL, grade VARCHAR(20) NOT NULL, manager_id VARCHAR(30), hire_date DATE NOT NULL, tenure_months INT NOT NULL, work_format VARCHAR(20), preferred_language VARCHAR(5), last_review_date DATE NOT NULL, FOREIGN KEY(manager_id) REFERENCES employee(id));
CREATE TABLE IF NOT EXISTS career_goal (employee_id VARCHAR(30) PRIMARY KEY, profile_id INT NOT NULL, FOREIGN KEY(employee_id) REFERENCES employee(id), FOREIGN KEY(profile_id) REFERENCES role_profile(id));
CREATE TABLE IF NOT EXISTS employee_skill (employee_id VARCHAR(30) NOT NULL, skill_id VARCHAR(80) NOT NULL, skill_level INT NOT NULL, PRIMARY KEY(employee_id,skill_id), FOREIGN KEY(employee_id) REFERENCES employee(id), FOREIGN KEY(skill_id) REFERENCES skill(id), CHECK(skill_level BETWEEN 0 AND 5));
CREATE TABLE IF NOT EXISTS career_event (id VARCHAR(30) PRIMARY KEY, title VARCHAR(200) NOT NULL, description TEXT, event_type VARCHAR(30), event_format VARCHAR(30), duration_hours DOUBLE NOT NULL, mandatory BOOLEAN NOT NULL);
CREATE TABLE IF NOT EXISTS event_role (event_id VARCHAR(30) NOT NULL, role_name VARCHAR(100) NOT NULL, PRIMARY KEY(event_id,role_name), FOREIGN KEY(event_id) REFERENCES career_event(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS event_grade (event_id VARCHAR(30) NOT NULL, grade VARCHAR(20) NOT NULL, PRIMARY KEY(event_id,grade), FOREIGN KEY(event_id) REFERENCES career_event(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS event_skill (event_id VARCHAR(30) NOT NULL, skill_id VARCHAR(80) NOT NULL, gain INT NOT NULL, max_level INT NOT NULL, prerequisite_level INT NOT NULL, PRIMARY KEY(event_id,skill_id), FOREIGN KEY(event_id) REFERENCES career_event(id) ON DELETE CASCADE, FOREIGN KEY(skill_id) REFERENCES skill(id), CHECK(max_level BETWEEN 0 AND 5));
CREATE TABLE IF NOT EXISTS event_session (event_id VARCHAR(30) NOT NULL, session_date DATE NOT NULL, PRIMARY KEY(event_id,session_date), FOREIGN KEY(event_id) REFERENCES career_event(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS activity_record (id VARCHAR(50) PRIMARY KEY, employee_id VARCHAR(30) NOT NULL, event_id VARCHAR(30) NOT NULL, activity_date DATE NOT NULL, due_date DATE, status VARCHAR(20) NOT NULL, completion_pct INT NOT NULL, score INT, feedback_rating INT, assigned_by VARCHAR(20), request_id VARCHAR(100) UNIQUE, FOREIGN KEY(employee_id) REFERENCES employee(id), FOREIGN KEY(event_id) REFERENCES career_event(id), CHECK(completion_pct BETWEEN 0 AND 100));
CREATE TABLE IF NOT EXISTS app_user (username VARCHAR(100) PRIMARY KEY, password_hash VARCHAR(100) NOT NULL, authority VARCHAR(20) NOT NULL, employee_id VARCHAR(30), FOREIGN KEY(employee_id) REFERENCES employee(id));

